import "oaidl.idl";
import "ocidl.idl";


[object,
 oleautomation, // use "automation" marshaler (oleaut32.dll)
 uuid(54E049DB-C39C-4025-B1EF-2FC0E5246277),
 helpstring("Interface for communicating a values over shared memory.")]
interface ISharedMem : IUnknown {
    HRESULT GetSize ([out,retval] unsigned int * size);
    HRESULT SetData ([in] unsigned int idx, [in] unsigned char val);
    HRESULT GetData ([in] unsigned int idx, [out,retval] unsigned char * val);
};



[version(1.0),
 uuid(8E42F33F-E5E3-46B4-8B39-0A03DCF338CC),
 helpstring("TestComponent module")]
library TestComponent {
    importlib("stdole2.tlb");

    [version(1.0),
     uuid(B7B84F73-8638-4EE5-A486-2C9455C0CD2B),
     helpstring("Class for testing shared memory")]
    coclass TestSharedMem {
        [default] interface ISharedMem;
    };
};
