import "oaidl.idl";
import "ocidl.idl";

[object,
 oleautomation, // use "automation" marshaler (oleaut32.dll)
 uuid(54E049DB-C39C-4025-B1EF-2FC0E5246277),
 helpstring("Shared memory handle.")]
interface IDataHandle : IUnknown {
    [helpstring("Get shared-mem segment address & size. The data might not be writable. Lifetime is managed by IDataHandle object.")]
    HRESULT GetData ([out] BYTE ** buffer, [out] unsigned int * size);
};

[version(1.0),
 uuid(8E42F33F-E5E3-46B4-8B39-0A03DCF338CC),
 helpstring("TestServerProxy module")]
library TestServerProxy {
    importlib("stdole2.tlb");

    [version(1.0),
        uuid(D84F768B-55F6-4B3A-AF68-9276C9488696),
        helpstring("Class for testing shared memory")]
    coclass DataHandleProxy {
        [default] interface IDataHandle;
        interface IMarshal;
    };
};
