import "oaidl.idl";
import "ocidl.idl";
import "ImageSource.idl";


[version(1.0),
 uuid(8E42F33F-E5E3-46B4-8B39-0A03DCF338CC),
 helpstring("ImageSourceProxy module")]
library ImageSourceProxy {
    importlib("stdole2.tlb");

    [version(1.0),
        uuid(9A7D97EB-1491-438E-B88C-234390D727F2),
        helpstring("Class for testing shared memory")]
        coclass ImageHandleProxy {
        [default] interface IImageHandle;
        interface IMarshal;
    };
};
